name: linode01-memadore-dev
services:
  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik-certs:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  blog:
    image: ghcr.io/memadore/memadore.dev:main
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog.rule=Host(`memadore.dev`)
      - traefik.http.routers.blog.entrypoints=websecure
      - traefik.http.routers.blog.tls.certresolver=letsencrypt
  motorsport-notes:
    image: ghcr.io/memadore/motorsport-notes:main
    labels:
      - traefik.enable=true
      - traefik.http.routers.motorsport-notes.rule=Host(`motorsport-notes.memadore.dev`)
      - traefik.http.routers.motorsport-notes.entrypoints=websecure
      - traefik.http.routers.motorsport-notes.tls.certresolver=letsencrypt
volumes:
  traefik-certs: {}
